import { defineConfig } from 'astro/config';

// The live domain. Used for canonical URLs and the sitemap endpoint.
// (The sitemap is generated by src/pages/sitemap.xml.js so it always matches
// the real, live pages — no extra dependency needed.)
export default defineConfig({
  site: 'https://www.schifskycompanies.com',
  trailingSlash: 'always', // match the old site's trailing-slash URLs
  build: {
    inlineStylesheets: 'auto',
    format: 'directory',
  },
});
